// Cruise brand metadata
export const BRANDS = {
  holland: {
    name: "Holland America Line",
    tag: "Taking you to extraordinary places",
    theme: "holland",
    short: "HAL",
    favicon: "../assets/favicons/holland.png",
  },
  princess: {
    name: "Princess Cruises",
    tag: "Come back new",
    theme: "princess",
    short: "PCL",
    favicon: "../assets/favicons/princess.png",
  },
  seabourn: {
    name: "Seabourn",
    tag: "Elegant, ultra-luxury cruises",
    theme: "seabourn",
    short: "SBN",
    favicon: "../assets/favicons/seabourn.png",
  },
  cunard: {
    name: "Cunard",
    tag: "Leaders in luxury ocean travel",
    theme: "cunard",
    short: "CUN",
    favicon: "../assets/favicons/cunard.png",
  },
};

// Example: dynamic list of intents
export const customerIntents = [
  { value: "newBooking", label: "New Booking" },
  { value: "modifyBooking", label: "Modify Booking" },
  { value: "cancelBooking", label: "Cancel Booking" },
  { value: "billingIssue", label: "Billing Issue" },
  { value: "luggageLost", label: "Luggage Lost" },
  { value: "shoreExcursion", label: "Shore Excursion Inquiry" },
  { value: "onboardCredit", label: "Onboard Credit Issue" },
  { value: "specialAssistance", label: "Special Assistance Request" },
];

export const cxOneAgents = [
  { value: "agent1", label: "Agent 1" },
  { value: "agent2", label: "Agent 2" },
  { value: "agent3", label: "Agent 3" },
  { value: "agent4", label: "Agent 4" },
  { value: "agent5", label: "Agent 5" },
];

// Example: Deliver mode options
export const deliverModes = [
  { value: "spoken", label: "Spoken", isTextIncluded: false },
  { value: "text", label: "Text", isTextIncluded: true },
  { value: "both", label: "Both Spoken and Text", isTextIncluded: true },
];

export const SAMPLE_API_RESPONSES = [
  {
    brand: "holland",
    logo: "/assets/logos/holland.png",
    phoneType: "Mobile",
    phoneTypeImage: "/assets/phoneTypes/mobile.png",
    phone: "+15551234567",
    email: "sample@email.com",
    customerId: "C-0001",
    callerName: "John Doe",
    ccn: "CCN-12345",
    loyalty: "5-Star Platinum",
    loyaltyLevel: "5",
    callerType: "D",
    callerImage: "/assets/icons/guest.png",
    intent: "newBooking",
    intentImage: "/assets/intents/newBooking2.png",
    booking: {
      number: "B-123",
      date: "2025-11-05 09:30",

      bookingNotes: "Sample notes for the agent.",
    },
    voyageType: "WC",
    voyageTypeText: "World Cruise",
    voyageTypeImage: "/assets/voyageTypes/worldCruise.png",
    mediaType: "Voice",
    authenticated: true,
    authStatus: {
      authenticated: true,
      status: "AI authenticated",
      details: "Customer authenticated via security questions.",
    },
    lang: "en-US",
    langFlag: "/assets/flags/english.png",
    transcript: "I want to do a new booking for next month.",
    transferTo: "Support Queue",
    routeEmail: true,
    routeSMS: false,
    routeChat: true,
    termsAndConditions: [
      { value: "cancelPolicy", label: "Accept Cancellation Policy" },
      { value: "refundTerms", label: "Agree to Refund Terms" },
      { value: "privacyGDPR", label: "Acknowledge Privacy Policy (GDPR)" },
      { value: "promoConsent", label: "Consent to Promotional Communication" },
      { value: "liabilityWaiver", label: "Accept Liability Waiver" },
      {
        value: "insurancePolicy",
        label: "Acknowledge Travel Insurance Policy",
      },
      { value: "behaviorPolicy", label: "Accept Onboard Behavior Policy" },
      { value: "paymentAuth", label: "Agree to Payment Authorization" },
      { value: "contractTerms", label: "Accept Cruise Contract Terms" },
      {
        value: "healthSafety",
        label: "Consent to Health and Safety Protocols",
      },
    ],
  },
  {
    brand: "cunard",
    logo: "/assets/logos/cunard.png",
    phoneType: "Landline",
    phoneTypeImage: "/assets/phoneTypes/landline.png",
    phone: "+493012345678",
    email: "lucas.müller@sample.com",
    customerId: "C-0002",
    callerName: "Lucas Müller",
    ccn: "CCN-23456",
    loyalty: "3-Star Platinum",
    loyaltyLevel: "3",
    callerType: "T",
    travelAdvisor: "Cosco Travels",
    travelAdvisorImage: "/assets/travelAdvisors/cosco.png",
    travelAdvisorInfo: {
      iata: "IATA-78901",
      clia: "CLIA-45678",
      agencyId: "AG-12345",
      agencyName: "Cosco Travel Agency",
    },
    intent: "modifyBooking",
    intentImage: "/assets/intents/modifyBooking.png",
    booking: {
      number: "B-234",
      date: "2025-11-06 14:00",

      bookingNotes: "Requested to modify the existing booking.",
    },
    voyageType: "GV",
    voyageTypeText: "Grand Voyage",
    voyageTypeImage: "/assets/voyageTypes/grandVoyage.png",
    mediaType: "Chat",
    authenticated: false,
    authStatus: {
      authenticated: false,
      status: "Failed authentication",
      details: "Customer failed security questions.",
    },
    lang: "de-DE",
    langFlag: "/assets/flags/german.png",
    transcript: "I want to modify my upcoming booking.",
    transferTo: "Reservations Queue",
    routeEmail: false,
    routeSMS: true,
    routeChat: true,
    termsAndConditions: [
      { value: "cancelPolicy", label: "Accept Cancellation Policy" },
      { value: "refundTerms", label: "Agree to Refund Terms" },
      { value: "privacyGDPR", label: "Acknowledge Privacy Policy (GDPR)" },
      { value: "promoConsent", label: "Consent to Promotional Communication" },
      { value: "liabilityWaiver", label: "Accept Liability Waiver" },
      {
        value: "insurancePolicy",
        label: "Acknowledge Travel Insurance Policy",
      },
      { value: "behaviorPolicy", label: "Accept Onboard Behavior Policy" },
      { value: "paymentAuth", label: "Agree to Payment Authorization" },
      { value: "contractTerms", label: "Accept Cruise Contract Terms" },
      {
        value: "healthSafety",
        label: "Consent to Health and Safety Protocols",
      },
    ],
  },
  {
    brand: "seabourn",
    logo: "/assets/logos/seabourn.png",
    phoneType: "Mobile",
    phoneTypeImage: "/assets/phoneTypes/mobile.png",
    phone: "+31612345678",
    email: "emma.dejong@sample.nl",
    customerId: "C-0003",
    callerName: "Emma de Jong",
    ccn: "CCN-34567",
    loyalty: "2-Star Platinum",
    loyaltyLevel: "2",
    callerType: "D",
    callerImage: "/assets/icons/guest.png",
    intent: "cancelBooking",
    intentImage: "/assets/intents/cancelBooking.png",
    booking: {
      number: "B-345",
      date: "2025-11-07 10:15",

      bookingNotes: "Customer wants to modify bed arrangement.",
    },
    voyageType: "BC",
    voyageTypeText: "Bingo/Charity Voyage",
    voyageTypeImage: "/assets/voyageTypes/bingoCruise.png",
    mediaType: "Voice",
    authenticated: true,
    authStatus: {
      authenticated: true,
      status: "Agent authenticated",
      details: "Customer authenticated via security questions.",
    },
    lang: "nl-NL",
    langFlag: "/assets/flags/dutch.png",
    transcript: "I want to cancel my upcoming booking.",
    transferTo: "Guest Services",
    routeEmail: true,
    routeSMS: true,
    routeChat: false,
    termsAndConditions: [
      { value: "cancelPolicy", label: "Accept Cancellation Policy" },
      { value: "refundTerms", label: "Agree to Refund Terms" },
      { value: "privacyGDPR", label: "Acknowledge Privacy Policy (GDPR)" },
      { value: "promoConsent", label: "Consent to Promotional Communication" },
      { value: "liabilityWaiver", label: "Accept Liability Waiver" },
      {
        value: "insurancePolicy",
        label: "Acknowledge Travel Insurance Policy",
      },
      { value: "behaviorPolicy", label: "Accept Onboard Behavior Policy" },
      { value: "paymentAuth", label: "Agree to Payment Authorization" },
      { value: "contractTerms", label: "Accept Cruise Contract Terms" },
      {
        value: "healthSafety",
        label: "Consent to Health and Safety Protocols",
      },
    ],
  },
  {
    brand: "princess",
    logo: "/assets/logos/princess.png",
    phoneType: "Landline",
    phoneTypeImage: "/assets/phoneTypes/landline.png",
    phone: "+442012345678",
    email: "sophie.brown@sample.co.uk",
    customerId: "C-0004",
    callerName: "Sophie Brown",
    ccn: "CCN-45678",
    loyalty: "1-Star Platinum",
    loyaltyLevel: "1",
    callerType: "T",
    travelAdvisorImage: "/assets/travelAdvisors/vacationToGo.jpg",
    travelAdvisor: "Vacation To Go",
    travelAdvisorInfo: {
      iata: "IATA-78901",
      clia: "CLIA-45678",
      agencyId: "AG-12345",
      agencyName: "Vacation To Go",
    },
    intent: "billingIssue",
    intentImage: "/assets/intents/billingIssue.jpg",
    booking: {
      number: "B-456",
      date: "2025-11-08 16:00",
      bookingNotes: "Customer requesting refund for canceled trip.",
    },
    voyageType: "FF",
    voyageTypeText: "Friends & Family Voyage",
    voyageTypeImage: "/assets/voyageTypes/friendsFamily.png",
    mediaType: "Email",
    authenticated: false,
    authStatus: {
      authenticated: false,
      status: "Not attempted",
      details: "Authentication not attempted .",
    },
    lang: "en-DE",
    langFlag: "/assets/flags/english.png",
    transcript: "I am facing issue with billing.",
    transferTo: "Billing Department",
    routeEmail: false,
    routeSMS: false,
    routeChat: false,
    termsAndConditions: [
      { value: "cancelPolicy", label: "Accept Cancellation Policy" },
      { value: "refundTerms", label: "Agree to Refund Terms" },
      { value: "privacyGDPR", label: "Acknowledge Privacy Policy (GDPR)" },
      { value: "promoConsent", label: "Consent to Promotional Communication" },
      { value: "liabilityWaiver", label: "Accept Liability Waiver" },
      {
        value: "insurancePolicy",
        label: "Acknowledge Travel Insurance Policy",
      },
      { value: "behaviorPolicy", label: "Accept Onboard Behavior Policy" },
      { value: "paymentAuth", label: "Agree to Payment Authorization" },
      { value: "contractTerms", label: "Accept Cruise Contract Terms" },
      {
        value: "healthSafety",
        label: "Consent to Health and Safety Protocols",
      },
    ],
  },
  {
    brand: "holland",
    logo: "/assets/logos/holland.png",
    phoneType: "Mobile",
    phoneTypeImage: "/assets/phoneTypes/mobile.png",
    phone: "+15557654321",
    email: "jason.williams@sample.com",
    customerId: "C-0005",
    callerName: "Jason Williams",
    ccn: "CCN-56789",
    loyalty: "2-Star Platinum",
    loyaltyLevel: "2",
    callerType: "D",
    callerImage: "/assets/icons/guest.png",
    intent: "newBooking",
    intentImage: "/assets/intents/newBooking2.png",
    booking: {
      number: "B-567",
      date: "2025-11-09 11:45",
      bookingNotes: "Interested in upgrading to premium suite.",
    },
    voyageType: "IL",
    voyageTypeText: "Inteline Cruise",
    voyageTypeImage: "/assets/voyageTypes/interline.png",
    mediaType: "Voice",
    authenticated: true,
    authStatus: {
      authenticated: true,
      status: "AI GDPR authenticated",
      details: "Customer authenticated via security questions.",
    },
    lang: "en-US",
    langFlag: "/assets/flags/german.png",
    transcript: "I want to do a new booking for next month.",
    transferTo: "Sales Queue",
    routeEmail: true,
    routeSMS: true,
    routeChat: true,
    termsAndConditions: [
      { value: "cancelPolicy", label: "Accept Cancellation Policy" },
      { value: "refundTerms", label: "Agree to Refund Terms" },
      { value: "privacyGDPR", label: "Acknowledge Privacy Policy (GDPR)" },
      { value: "promoConsent", label: "Consent to Promotional Communication" },
      { value: "liabilityWaiver", label: "Accept Liability Waiver" },
      {
        value: "insurancePolicy",
        label: "Acknowledge Travel Insurance Policy",
      },
      { value: "behaviorPolicy", label: "Accept Onboard Behavior Policy" },
      { value: "paymentAuth", label: "Agree to Payment Authorization" },
      { value: "contractTerms", label: "Accept Cruise Contract Terms" },
      {
        value: "healthSafety",
        label: "Consent to Health and Safety Protocols",
      },
    ],
  },
  {
    brand: "seabourn",
    logo: "/assets/logos/seabourn.png",
    phoneType: "Landline",
    phoneTypeImage: "/assets/phoneTypes/landline.png",
    phone: "+31201234567",
    email: "mark.visser@sample.nl",
    customerId: "C-0006",
    callerName: "Mark Visser",
    ccn: "CCN-67890",
    loyalty: "1-Star Platinum",
    loyaltyLevel: "1",
    callerType: "T",
    travelAdvisorImage: "/assets/travelAdvisors/cosco.png",
    travelAdvisor: "Cosco Travels",
    travelAdvisorInfo: {
      iata: "IATA-78901",
      clia: "CLIA-45678",
      agencyId: "AG-12345",
      agencyName: "Cosco Travel Agency",
    },
    intent: "modifyBooking",
    intentImage: "/assets/intents/modifyBooking.png",
    booking: {
      number: "B-678",
      date: "2025-11-10 08:00",
      bookingNotes: "Requested itinerary changes for cruise trip.",
    },
    voyageType: "WC",
    voyageTypeText: "World Cruise",
    voyageTypeImage: "/assets/voyageTypes/worldCruise.png",
    mediaType: "Voice",
    authenticated: true,
    authStatus: {
      authenticated: true,
      status: "Incomplete authenticated",
      details: "Customer authenticated via security questions.",
    },
    lang: "en-NL",
    langFlag: "/assets/flags/dutch.png",
    transcript: "I want to modify my upcoming booking.",
    transferTo: "Operations Queue",
    routeEmail: true,
    routeSMS: false,
    routeChat: false,
    termsAndConditions: [
      { value: "cancelPolicy", label: "Accept Cancellation Policy" },
      { value: "refundTerms", label: "Agree to Refund Terms" },
      { value: "privacyGDPR", label: "Acknowledge Privacy Policy (GDPR)" },
      { value: "promoConsent", label: "Consent to Promotional Communication" },
      { value: "liabilityWaiver", label: "Accept Liability Waiver" },
      {
        value: "insurancePolicy",
        label: "Acknowledge Travel Insurance Policy",
      },
      { value: "behaviorPolicy", label: "Accept Onboard Behavior Policy" },
      { value: "paymentAuth", label: "Agree to Payment Authorization" },
      { value: "contractTerms", label: "Accept Cruise Contract Terms" },
      {
        value: "healthSafety",
        label: "Consent to Health and Safety Protocols",
      },
    ],
  },
  {
    brand: "princess",
    logo: "/assets/logos/princess.png",
    phoneType: "Mobile",
    phoneTypeImage: "/assets/phoneTypes/mobile.png",
    phone: "+14151234567",
    email: "olivia.martinez@sample.com",
    customerId: "C-0007",
    callerName: "Olivia Martinez",
    ccn: "CCN-78901",
    loyalty: "3-Star Platinum",
    loyaltyLevel: "3",
    callerType: "D",
    callerImage: "/assets/icons/guest.png",
    intent: "luggageLost",
    intentImage: "/assets/intents/luggageLost.png",
    booking: {
      number: "B-789",
      date: "2025-11-11 12:30",
      bookingNotes: "Reported missing luggage after arrival.",
    },
    voyageType: "GV",
    voyageTypeText: "Grand Voyage",
    voyageTypeImage: "/assets/voyageTypes/grandVoyage.png",
    mediaType: "Voice",
    authenticated: false,
    authStatus: {
      authenticated: false,
      status: "Failed authentication",
      details: "Customer failed security questions.",
    },
    lang: "en-US",
    langFlag: "/assets/flags/english.png",
    transcript: "Caller reported lost baggage.",
    transferTo: "Claims Department",
    routeEmail: true,
    routeSMS: false,
    routeChat: true,
    termsAndConditions: [
      { value: "cancelPolicy", label: "Accept Cancellation Policy" },
      { value: "refundTerms", label: "Agree to Refund Terms" },
      { value: "privacyGDPR", label: "Acknowledge Privacy Policy (GDPR)" },
      { value: "promoConsent", label: "Consent to Promotional Communication" },
      { value: "liabilityWaiver", label: "Accept Liability Waiver" },
      {
        value: "insurancePolicy",
        label: "Acknowledge Travel Insurance Policy",
      },
      { value: "behaviorPolicy", label: "Accept Onboard Behavior Policy" },
      { value: "paymentAuth", label: "Agree to Payment Authorization" },
      { value: "contractTerms", label: "Accept Cruise Contract Terms" },
      {
        value: "healthSafety",
        label: "Consent to Health and Safety Protocols",
      },
    ],
  },
  {
    brand: "holland",
    logo: "/assets/logos/holland.png",
    phoneType: "Landline",
    phoneTypeImage: "/assets/phoneTypes/landline.png",
    phone: "+498912345678",
    email: "katrin.schmidt@sample.de",
    customerId: "C-0008",
    callerName: "Katrin Schmidt",
    ccn: "CCN-89012",
    loyalty: "5-Star Platinum",
    loyaltyLevel: "5",
    callerType: "T",
    travelAdvisorImage: "/assets/travelAdvisors/vacationToGo.jpg",
    travelAdvisor: "Vacation To Go",
    travelAdvisorInfo: {
      iata: "IATA-78901",
      clia: "CLIA-45678",
      agencyId: "AG-12345",
      agencyName: "Vacation To Go",
    },
    intent: "billingIssue",
    intentImage: "/assets/intents/billingIssue.jpg",
    booking: {
      number: "B-890",
      date: "2025-11-12 09:45",
      bookingNotes: "Reported issue with credit card payment.",
    },
    voyageType: "BC",
    voyageTypeText: "Bingo/Charity Voyage",
    voyageTypeImage: "/assets/voyageTypes/bingoCruise.png",
    mediaType: "Chat",
    authenticated: true,
    authStatus: {
      authenticated: true,
      status: "AI authenticated",
      details: "Customer authenticated via security questions.",
    },
    lang: "de-DE",
    langFlag: "/assets/flags/german.png",
    transcript: "I am facing issue with billing.",
    transferTo: "Billing Support",
    routeEmail: true,
    routeSMS: true,
    routeChat: true,
    termsAndConditions: [
      { value: "cancelPolicy", label: "Accept Cancellation Policy" },
      { value: "refundTerms", label: "Agree to Refund Terms" },
      { value: "privacyGDPR", label: "Acknowledge Privacy Policy (GDPR)" },
      { value: "promoConsent", label: "Consent to Promotional Communication" },
      { value: "liabilityWaiver", label: "Accept Liability Waiver" },
      {
        value: "insurancePolicy",
        label: "Acknowledge Travel Insurance Policy",
      },
      { value: "behaviorPolicy", label: "Accept Onboard Behavior Policy" },
      { value: "paymentAuth", label: "Agree to Payment Authorization" },
      { value: "contractTerms", label: "Accept Cruise Contract Terms" },
      {
        value: "healthSafety",
        label: "Consent to Health and Safety Protocols",
      },
    ],
  },
  {
    brand: "cunard",
    logo: "/assets/logos/cunard.png",
    phoneType: "Mobile",
    phoneTypeImage: "/assets/phoneTypes/mobile.png",
    phone: "+15553456789",
    email: "will.johnson@sample.com",
    customerId: "C-0009",
    callerName: "William Johnson",
    ccn: "CCN-90123",
    loyalty: "4-Star Platinum",
    loyaltyLevel: "4",
    callerType: "D",
    callerImage: "/assets/icons/guest.png",
    intent: "modifyBooking",
    intentImage: "/assets/intents/modifyBooking.png",
    booking: {
      number: "B-901",
      date: "2025-11-13 15:00",
      bookingNotes: "Requested wheelchair assistance for boarding.",
    },
    voyageType: "FF",
    voyageTypeText: "Friends & Family Voyage",
    voyageTypeImage: "/assets/voyageTypes/friendsFamily.png",
    mediaType: "Voice",
    authenticated: true,
    authStatus: {
      authenticated: true,
      status: "AI GDPR authenticated",
      details: "Customer authenticated via security questions.",
    },
    lang: "en-US",
    langFlag: "/assets/flags/dutch.png",
    transcript: "I want to modify my upcoming booking.",
    transferTo: "Accessibility Desk",
    routeEmail: false,
    routeSMS: false,
    routeChat: true,
    termsAndConditions: [
      { value: "cancelPolicy", label: "Accept Cancellation Policy" },
      { value: "refundTerms", label: "Agree to Refund Terms" },
      { value: "privacyGDPR", label: "Acknowledge Privacy Policy (GDPR)" },
      { value: "promoConsent", label: "Consent to Promotional Communication" },
      { value: "liabilityWaiver", label: "Accept Liability Waiver" },
      {
        value: "insurancePolicy",
        label: "Acknowledge Travel Insurance Policy",
      },
      { value: "behaviorPolicy", label: "Accept Onboard Behavior Policy" },
      { value: "paymentAuth", label: "Agree to Payment Authorization" },
      { value: "contractTerms", label: "Accept Cruise Contract Terms" },
      {
        value: "healthSafety",
        label: "Consent to Health and Safety Protocols",
      },
    ],
  },
  {
    brand: "princess",
    logo: "/assets/logos/princess.png",
    phoneType: "Landline",
    phoneTypeImage: "/assets/phoneTypes/landline.png",
    phone: "+15552345678",
    email: "sarah.jones@sample.com",
    customerId: "C-0010",
    callerName: "Sarah Jones",
    ccn: "CCN-01234",
    loyalty: "4-Star Platinum",
    loyaltyLevel: "4",
    callerType: "T",
    travelAdvisorImage: "",
    travelAdvisor: "N/A",
    travelAdvisorInfo: {
      iata: "NA",
      clia: "NA",
      agencyId: "NA",
      agencyName: "NA",
    },
    intent: "newBooking",
    intentImage: "/assets/intents/newBooking2.png",
    booking: {
      number: "B-012",
      date: "2025-11-14 18:00",
      bookingNotes: "Checking cabin availability for next month.",
    },
    voyageType: "IL",
    voyageTypeText: "Interline Cruise",
    voyageTypeImage: "/assets/voyageTypes/interline.png",
    mediaType: "Voice",
    authenticated: true,
    authStatus: {
      authenticated: true,
      status: "AI Incompete authenticated",
      details: "Customer authenticated via security questions.",
    },
    lang: "en-DE",
    langFlag: "/assets/flags/english.png",
    transcript: "I want to do a new booking for next month.",
    transferTo: "Sales Queue",
    routeEmail: false,
    routeSMS: false,
    routeChat: false,
    termsAndConditions: [
      { value: "cancelPolicy", label: "Accept Cancellation Policy" },
      { value: "refundTerms", label: "Agree to Refund Terms" },
      { value: "privacyGDPR", label: "Acknowledge Privacy Policy (GDPR)" },
      { value: "promoConsent", label: "Consent to Promotional Communication" },
      { value: "liabilityWaiver", label: "Accept Liability Waiver" },
      {
        value: "insurancePolicy",
        label: "Acknowledge Travel Insurance Policy",
      },
      { value: "behaviorPolicy", label: "Accept Onboard Behavior Policy" },
      { value: "paymentAuth", label: "Agree to Payment Authorization" },
      { value: "contractTerms", label: "Accept Cruise Contract Terms" },
      {
        value: "healthSafety",
        label: "Consent to Health and Safety Protocols",
      },
    ],
  },
];
